In [20]:
import numpy as np

!Important: provided example not evaluates special cases as "no no solution", "many solutions", etc.

In [28]:
A=np.matrix([[1.0 , -2.0,  3.0,  4.0],
             [1.0, 0.0, -1.0,  1.0],
             [2.0,  -2.0, 2.0,  5.0],
             [0.0,  -7.0,  3.0, 1.0]])       # coeficients



B=np.matrix([[3,7,1,3],
             [1,-6,6,9],
             [4,4,-7,1],
             [-1,3,8,2]])       # coeficients
C=np.matrix([[0,1,2,1],
             [6,-2,3,4],
             [0,3,4,-3],
             [0,-4,3,1]])       # coeficients
D=np.matrix([[3,7,1,3],
             [1,-6,6,8],
             [4,4,-7,1],
             [4,16,2,0]])       # coeficients
E=np.matrix([[1,2,1,0],
             [2,5,0,4],
             [14,-8,4,1],
             [4,10,0,8]])       # coeficients

b=(np.matrix([11,-4,7,2])).transpose()  # vector b
b2=(np.matrix([37,11,38,-1])).transpose()  # vector b
b3=(np.matrix([2,-15,10,-2])).transpose()  # vector b
b4=(np.matrix([40,19,36,48])).transpose()  # vector b
b5=(np.matrix([-4,3,7,2])).transpose()  # vector b
#b=np.matrix([[2],[0],[9],[7]]) # alternative


In [29]:
n=(np.shape(A))[0]   # number of equations
nb=(np.shape(b))[1]  # number of solutions

In [30]:
A1=np.hstack((A,b))  # expanding matrix
print(A1)

[[ 1. -2.  3.  4. 11.]
 [ 1.  0. -1.  1. -4.]
 [ 2. -2.  2.  5.  7.]
 [ 0. -7.  3.  1.  2.]]


In [31]:
# forward step
for i in range (0,n-1):
    for j in range (i+1,n):
        if A1[i,i] != 0:  # Add this condition to check if A1[i,i] is non-zero
            A1[j,i:n+nb]=A1[j,i:n+nb]-A1[i,i:n+nb]*A1[j,i]/A1[i,i]
        A1[j,i]=0

print(A1)


#  backward step:
x = np.zeros(shape=(n,nb))
for i in range (n-1,-1,-1):
    if A1[i,i] != 0:  # Add this condition to check if A1[i,i] is non-zero
        x[i,:] = (A1[i,n:n+nb]-A1[i,i+1:n]*x[i+1:n,:]) / A1[i,i]
    else:
        # Handle the case where A1[i,i] is zero (division by zero)
        # This could be an error condition for your specific problem
        # Adjust the logic here to fit your problem's requirements
        pass

print(x)

[[  1.   -2.    3.    4.   11. ]
 [  0.    2.   -4.   -3.  -15. ]
 [  0.    0.    0.    0.    0. ]
 [  0.    0.    0.   -9.5 -50.5]]
[[-9.31578947]
 [ 0.47368421]
 [ 0.        ]
 [ 5.31578947]]


In [32]:
np.matmul(A,x)

matrix([[11.],
        [-4.],
        [ 7.],
        [ 2.]])