In [26]:
import numpy as np
"""A=np.matrix([[1.0 , -2.0,  3.0,  4.0],
             [1.0, 0.0, -1.0,  1.0],
             [2.0,  -2.0, 2.0,  5.0],
             [0.0,  -7.0,  3.0, 1.0]])       # coeficients"""



"""A=np.matrix([[3,7,1,3],
             [1,-6,6,9],
             [4,4,-7,1],
             [-1,3,8,2]])       # coeficients"""
"""A=np.matrix([[0,1,2,1],
             [6,-2,3,4],
             [0,3,4,-3],
             [0,-4,3,1]])       # coeficients"""
"""A=np.matrix([[3,7,1,3],
             [1,-6,6,8],
             [4,4,-7,1],
             [4,16,2,0]])       # coeficients"""
A=np.matrix([[1,2,1,0],
             [2,5,0,4],
             [14,-8,4,1],
             [4,10,0,8]])       # coeficients

"""b=(np.matrix([11,-4,7,2])).transpose()  # vector b"""
"""b=(np.matrix([37,11,38,-1])).transpose()  # vector b"""
"""b=(np.matrix([2,-15,10,-2])).transpose()  # vector b"""
"""b=(np.matrix([40,19,36,48])).transpose()  # vector b"""
b=(np.matrix([-4,3,7,2])).transpose()  # vector b
n=(np.shape(A))[0]   # number of equations

# Determine the number of solutions by checking the second dimension of vector b
nb=(np.shape(b))[1]  # number of solutions

# Combine the A matrix and b vector into an augmented matrix A1
A1=np.hstack((A,b))   # Augmented matrix creation

# Print the augmented matrix A1
print(A1)

eps = 1e-10
A1=np.hstack((A,b))  # expanding matrix
# Forward elimination step of Gaussian elimination
for i in range(0, n - 1):  # Loop over each row starting from the first to the penultimate
    for j in range(i + 1, n):  # Loop over each row below the current row i
        if np.abs(A1[i, i]) > eps:  # Check if the pivot element is not too small
            # Perform row operations to make elements below the pivot in the current column zero
            A1[j, i:n + nb] = A1[j, i:n + nb] - A1[i, i:n + nb] * A1[j, i] / A1[i, i]
            A1[j, i] = 0  # Set the element below the pivot to zero after the operation
    print(A1); print(" ");


print(A1)

# Backward substitution step of Gaussian elimination
x = np.zeros(shape=(n, nb))  # Initialize the solution vector x with zeros
for i in range(n - 1, -1, -1):  # Loop from the last row to the first row
    if np.abs(A1[i, i]) <= eps:  # Check if the diagonal element is effectively zero
        if np.abs(A1[i, n - 1]) <= eps:  # Check if the corresponding b element is effectively zero
            if np.abs(A1[i, n]) > eps:  # Inconsistent system check
                print("No solution")
            else:  # System has many solutions
                print("Many solutions")
            continue
    if np.abs(A1[i, i]) > eps:  # If the diagonal element is not too small
        # Calculate the solution for the current variable
        x[i, :] = (A1[i, n:n + nb] - A1[i, i + 1:n] * x[i + 1:n, :]) / A1[i, i]
        print(x); print(" ");

# Print the solution vector x
print(x)

# Print the solution statement
print("Solution:")
print(x)
print(" ")

# Print the validation step to check if Ax = b
print("Ax-b:")
print("Validation")
print((np.matmul(A, x)))

[[ 1  2  1  0 -4]
 [ 2  5  0  4  3]
 [14 -8  4  1  7]
 [ 4 10  0  8  2]]
[[  1   2   1   0  -4]
 [  0   1  -2   4  11]
 [  0 -36 -10   1  63]
 [  0   2  -4   8  18]]
 
[[  1   2   1   0  -4]
 [  0   1  -2   4  11]
 [  0   0 -82 145 459]
 [  0   0   0   0  -4]]
 
[[  1   2   1   0  -4]
 [  0   1  -2   4  11]
 [  0   0 -82 145 459]
 [  0   0   0   0  -4]]
 
[[  1   2   1   0  -4]
 [  0   1  -2   4  11]
 [  0   0 -82 145 459]
 [  0   0   0   0  -4]]
No solution
[[ 0.        ]
 [ 0.        ]
 [-5.59756098]
 [ 0.        ]]
 
[[ 0.        ]
 [-0.19512195]
 [-5.59756098]
 [ 0.        ]]
 
[[ 1.98780488]
 [-0.19512195]
 [-5.59756098]
 [ 0.        ]]
 
[[ 1.98780488]
 [-0.19512195]
 [-5.59756098]
 [ 0.        ]]
Solution:
[[ 1.98780488]
 [-0.19512195]
 [-5.59756098]
 [ 0.        ]]
 
Ax-b:
Validation
[[-4.]
 [ 3.]
 [ 7.]
 [ 6.]]
